// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDidjpJOBHloLL86e1v-1DUwOYc8Lolekg',
    appId: '1:856692076467:web:1bbb7845a56f107e68a5c6',
    messagingSenderId: '856692076467',
    projectId: 'notes-app-91908',
    authDomain: 'notes-app-91908.firebaseapp.com',
    storageBucket: 'notes-app-91908.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS_D8x8LzXrrDljyPb8aWVJ37lfZQYjog',
    appId: '1:856692076467:android:5dbe952b5d266da968a5c6',
    messagingSenderId: '856692076467',
    projectId: 'notes-app-91908',
    storageBucket: 'notes-app-91908.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbRZgDFSt6h388Ad1FuW26qHQL9LTn2pE',
    appId: '1:856692076467:ios:e7e5660fd960529c68a5c6',
    messagingSenderId: '856692076467',
    projectId: 'notes-app-91908',
    storageBucket: 'notes-app-91908.appspot.com',
    androidClientId: '856692076467-p4nsdo0lthu8o8l3ohpi88avn9mt8aiu.apps.googleusercontent.com',
    iosClientId: '856692076467-qpjdrfb0vp8j93vfeqt2kfko4f8cki2m.apps.googleusercontent.com',
    iosBundleId: 'com.example.note',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbRZgDFSt6h388Ad1FuW26qHQL9LTn2pE',
    appId: '1:856692076467:ios:e7e5660fd960529c68a5c6',
    messagingSenderId: '856692076467',
    projectId: 'notes-app-91908',
    storageBucket: 'notes-app-91908.appspot.com',
    androidClientId: '856692076467-p4nsdo0lthu8o8l3ohpi88avn9mt8aiu.apps.googleusercontent.com',
    iosClientId: '856692076467-qpjdrfb0vp8j93vfeqt2kfko4f8cki2m.apps.googleusercontent.com',
    iosBundleId: 'com.example.note',
  );
}
